//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitap21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giaovien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giaovien()
        {
            this.LopSH = new HashSet<LopSH>();
        }
    
        public string MaGV { get; set; }
        public string HotenGV { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string diachi { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string emailDCT { get; set; }
        public string maDV { get; set; }
        public string hocvi { get; set; }
        public string chucdanh { get; set; }
        public string chucvu { get; set; }
        public string password { get; set; }
        public string website { get; set; }
        public string tenviet { get; set; }
        public string status { get; set; }
        public string accright { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopSH> LopSH { get; set; }
    }
}
