//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitap21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSH_SV
    {

        public string MaLSH { get; set; }
        public string MaSV { get; set; }
        public Nullable<int> curSem { get; set; }
        public Nullable<int> tichluy { get; set; }
        public Nullable<int> GCP { get; set; }
        public Nullable<int> ECP { get; set; }
        public string Status { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> CN2 { get; set; }
    
        public virtual LopSH LopSH { get; set; }
        public virtual Sinhvien Sinhvien { get; set; }
    }
}
