//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitap21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sinhvien()
        {
            this.LSH_SV = new HashSet<LSH_SV>();
        }
    
        public string Masv { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string TenViet { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Noisinh { get; set; }
        public Nullable<bool> goitinh { get; set; }
        public string diachi { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string emailDCT { get; set; }
        public Nullable<int> diemTS { get; set; }
        public string accno { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public string ghichu { get; set; }
        public string makh { get; set; }
        public string scmnd { get; set; }
        public string tenKD { get; set; }
        public string special { get; set; }
        public Nullable<int> diemRl { get; set; }
        public Nullable<int> QDTT { get; set; }
        public Nullable<int> CDRTH { get; set; }
        public string SCMND_IMG { get; set; }
        public string CapDT { get; set; }
        public Nullable<int> ks { get; set; }
        public string dantoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSH_SV> LSH_SV { get; set; }
    }
}
